# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: article.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='article.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rarticle.proto\"\x0e\n\x0c\x41rticleEmpty\"5\n\x10\x41rticleListReply\x12!\n\x08\x61rticles\x18\x01 \x03(\x0b\x32\x0f.ArticleRequest\"\x8c\x01\n\x0e\x41rticleRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x63lassify\x18\x02 \x01(\x05\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x10\n\x08isPublic\x18\x04 \x01(\x08\x12\r\n\x05title\x18\x05 \x01(\t\x12\x0b\n\x03url\x18\x06 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x07 \x01(\t\x12\r\n\x05\x63over\x18\x08 \x01(\t\"\x1b\n\rArticleIdOnly\x12\n\n\x02id\x18\x01 \x01(\t2\xed\x01\n\x07\x61rticle\x12-\n\x07getList\x12\r.ArticleEmpty\x1a\x11.ArticleListReply\"\x00\x12,\n\x07getById\x12\x0e.ArticleIdOnly\x1a\x0f.ArticleRequest\"\x00\x12,\n\x06insert\x12\x0f.ArticleRequest\x1a\x0f.ArticleRequest\"\x00\x12,\n\x06update\x12\x0f.ArticleRequest\x1a\x0f.ArticleRequest\"\x00\x12)\n\x06remove\x12\x0e.ArticleIdOnly\x1a\r.ArticleEmpty\"\x00\x62\x06proto3'
)




_ARTICLEEMPTY = _descriptor.Descriptor(
  name='ArticleEmpty',
  full_name='ArticleEmpty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=31,
)


_ARTICLELISTREPLY = _descriptor.Descriptor(
  name='ArticleListReply',
  full_name='ArticleListReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='articles', full_name='ArticleListReply.articles', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=86,
)


_ARTICLEREQUEST = _descriptor.Descriptor(
  name='ArticleRequest',
  full_name='ArticleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ArticleRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='classify', full_name='ArticleRequest.classify', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='author', full_name='ArticleRequest.author', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isPublic', full_name='ArticleRequest.isPublic', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='ArticleRequest.title', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='ArticleRequest.url', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='ArticleRequest.content', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cover', full_name='ArticleRequest.cover', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=229,
)


_ARTICLEIDONLY = _descriptor.Descriptor(
  name='ArticleIdOnly',
  full_name='ArticleIdOnly',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ArticleIdOnly.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=258,
)

_ARTICLELISTREPLY.fields_by_name['articles'].message_type = _ARTICLEREQUEST
DESCRIPTOR.message_types_by_name['ArticleEmpty'] = _ARTICLEEMPTY
DESCRIPTOR.message_types_by_name['ArticleListReply'] = _ARTICLELISTREPLY
DESCRIPTOR.message_types_by_name['ArticleRequest'] = _ARTICLEREQUEST
DESCRIPTOR.message_types_by_name['ArticleIdOnly'] = _ARTICLEIDONLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ArticleEmpty = _reflection.GeneratedProtocolMessageType('ArticleEmpty', (_message.Message,), {
  'DESCRIPTOR' : _ARTICLEEMPTY,
  '__module__' : 'article_pb2'
  # @@protoc_insertion_point(class_scope:ArticleEmpty)
  })
_sym_db.RegisterMessage(ArticleEmpty)

ArticleListReply = _reflection.GeneratedProtocolMessageType('ArticleListReply', (_message.Message,), {
  'DESCRIPTOR' : _ARTICLELISTREPLY,
  '__module__' : 'article_pb2'
  # @@protoc_insertion_point(class_scope:ArticleListReply)
  })
_sym_db.RegisterMessage(ArticleListReply)

ArticleRequest = _reflection.GeneratedProtocolMessageType('ArticleRequest', (_message.Message,), {
  'DESCRIPTOR' : _ARTICLEREQUEST,
  '__module__' : 'article_pb2'
  # @@protoc_insertion_point(class_scope:ArticleRequest)
  })
_sym_db.RegisterMessage(ArticleRequest)

ArticleIdOnly = _reflection.GeneratedProtocolMessageType('ArticleIdOnly', (_message.Message,), {
  'DESCRIPTOR' : _ARTICLEIDONLY,
  '__module__' : 'article_pb2'
  # @@protoc_insertion_point(class_scope:ArticleIdOnly)
  })
_sym_db.RegisterMessage(ArticleIdOnly)



_ARTICLE = _descriptor.ServiceDescriptor(
  name='article',
  full_name='article',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=261,
  serialized_end=498,
  methods=[
  _descriptor.MethodDescriptor(
    name='getList',
    full_name='article.getList',
    index=0,
    containing_service=None,
    input_type=_ARTICLEEMPTY,
    output_type=_ARTICLELISTREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getById',
    full_name='article.getById',
    index=1,
    containing_service=None,
    input_type=_ARTICLEIDONLY,
    output_type=_ARTICLEREQUEST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='insert',
    full_name='article.insert',
    index=2,
    containing_service=None,
    input_type=_ARTICLEREQUEST,
    output_type=_ARTICLEREQUEST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='update',
    full_name='article.update',
    index=3,
    containing_service=None,
    input_type=_ARTICLEREQUEST,
    output_type=_ARTICLEREQUEST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='remove',
    full_name='article.remove',
    index=4,
    containing_service=None,
    input_type=_ARTICLEIDONLY,
    output_type=_ARTICLEEMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ARTICLE)

DESCRIPTOR.services_by_name['article'] = _ARTICLE

# @@protoc_insertion_point(module_scope)
