# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import article_pb2 as article__pb2


class articleStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getList = channel.unary_unary(
        '/article/getList',
        request_serializer=article__pb2.ArticleEmpty.SerializeToString,
        response_deserializer=article__pb2.ArticleListReply.FromString,
        )
    self.getById = channel.unary_unary(
        '/article/getById',
        request_serializer=article__pb2.ArticleIdOnly.SerializeToString,
        response_deserializer=article__pb2.ArticleRequest.FromString,
        )
    self.insert = channel.unary_unary(
        '/article/insert',
        request_serializer=article__pb2.ArticleRequest.SerializeToString,
        response_deserializer=article__pb2.ArticleRequest.FromString,
        )
    self.update = channel.unary_unary(
        '/article/update',
        request_serializer=article__pb2.ArticleRequest.SerializeToString,
        response_deserializer=article__pb2.ArticleRequest.FromString,
        )
    self.remove = channel.unary_unary(
        '/article/remove',
        request_serializer=article__pb2.ArticleIdOnly.SerializeToString,
        response_deserializer=article__pb2.ArticleEmpty.FromString,
        )


class articleServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def insert(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def update(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def remove(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_articleServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getList': grpc.unary_unary_rpc_method_handler(
          servicer.getList,
          request_deserializer=article__pb2.ArticleEmpty.FromString,
          response_serializer=article__pb2.ArticleListReply.SerializeToString,
      ),
      'getById': grpc.unary_unary_rpc_method_handler(
          servicer.getById,
          request_deserializer=article__pb2.ArticleIdOnly.FromString,
          response_serializer=article__pb2.ArticleRequest.SerializeToString,
      ),
      'insert': grpc.unary_unary_rpc_method_handler(
          servicer.insert,
          request_deserializer=article__pb2.ArticleRequest.FromString,
          response_serializer=article__pb2.ArticleRequest.SerializeToString,
      ),
      'update': grpc.unary_unary_rpc_method_handler(
          servicer.update,
          request_deserializer=article__pb2.ArticleRequest.FromString,
          response_serializer=article__pb2.ArticleRequest.SerializeToString,
      ),
      'remove': grpc.unary_unary_rpc_method_handler(
          servicer.remove,
          request_deserializer=article__pb2.ArticleIdOnly.FromString,
          response_serializer=article__pb2.ArticleEmpty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'article', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
